### ISSUE TITLE
Adding support for other languages 

### ISSUE THREAD

**Issue by yagyesh-bobde** [abhaybabbar/CodeDocsGPT#1]
Aim: To add support for more programming languages
- [x] Solidity

File to be changed: 
1. https://github.com/abhaybabbar/CodeDocsGPT/blob/main/extension.js

Can add more languages in future

**Comment by yagyesh-bobde** [comment]
do I only need to add the comment start and end for the new language to make it supportable??

**Comment by abhaybabbar** [comment]
@yagyesh-bobde Yes, we only need to add comment start and end. Thank you for making the changes. 
This issue would be closed.
